openapi: 3.1.0
x-stoplight:
  id: 79o5ggwjn9oo5
info:
  title: firma_verification_ms
  version: '1.0'
servers:
  - url: 'http://localhost:8093'
paths:
  /verification:
    post:
      summary: ''
      operationId: post-verification
      responses:
        '200':
          description: OK
components:
  schemas: {}
