openapi: 3.1.0
x-stoplight:
  id: 1kmbeivh9wh2b
info:
  title: firma_interface
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /interface:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-interface
components:
  schemas: {}
