openapi: 3.1.0
info:
  title: Micro-servicio de Verificación
  version: '1.0'
  summary: 'Verifica la autenticidad e integridad de un archivo, su autor y firma'
  description: ''
servers:
  - url: 'http://localhost:8093'
paths:
  /verification:
    post:
      summary: Verificar documento
      operationId: post-verification
      responses:
        '200':
          description: 'OK: se procesó la firma'
          content:
            application/json:
              schema:
                type: object
                properties:
                  isAuthenticated:
                    type: boolean
                  isNotAltered:
                    type: boolean
        '400':
          description: 'Bad Request: faltan parámetros'
          content:
            application/json:
              schema:
                type: object
                properties:
                  parameters:
                    type: array
                    items:
                      type: string
        '422':
          description: 'Unprocessable Entity (WebDAV): los parámetros están pero no son procesables'
          content:
            application/json:
              schema:
                type: object
                properties:
                  parameters:
                    type: array
                    items:
                      type: string
      description: 'Se le pasa un string de binarios, el usuario y la firma, y la API determina si el archivo no ha sido modificado y pertenece a quien se asume pertenecer'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                blob:
                  type: string
                  description: Una cadena con el binario del archivo codificado en base64
                userId:
                  type: integer
                  description: El ID del usuario en la base de datos de firma
                sign:
                  type: string
                  description: base64
      parameters: []
components:
  schemas: {}
  securitySchemes: {}
