openapi: 3.1.0
x-stoplight:
  id: 5lkg3h9nin79e
info:
  title: firma_ag
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /grahql:
    post:
      summary: ''
      operationId: post-grahql
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
components:
  schemas: {}
